version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/go/src/github.com/heron182/cloud-account-api
    working_dir: /go/src/github.com/heron182/cloud-account-api
    ports:
      - 8080:8080
    networks:
      - dev
    depends_on:
      - db

  db:
    image: mongo
    networks:
      - dev

networks:
  dev: